# Generated by Django 4.2.5 on 2023-09-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('flat_booked', models.CharField(max_length=255)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('creation_log', models.TextField()),
                ('booking_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
