# Generated by Django 4.2.5 on 2023-09-22 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_api_call', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
